version: "3.7"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/withtypes/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "typeInDocker"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379
